
[functions]
# Define edge functions here

[functions.telegram-webhook-proxy]
verify_jwt = false

[functions.telegram-process-command]
verify_jwt = false

[functions.telegram-send-message]
verify_jwt = false
