
import { InventoryItem } from "@/types/inventory";

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'Toner Cartridge',
    category: 'Toner',
    brand: 'Canon',
    model: 'IR2525',
    currentStock: 15,
    minStockLevel: 5,
    maxStockLevel: 30,
    reorderPoint: 10,
    unitCost: 2500,
    unitPrice: 3000,
    location: 'Warehouse A',
    lastRestocked: '2023-01-15',
    createdAt: '2023-01-01',
    modelId: 'model-1',
    brandId: 'brand-1',
    type: 'Toner',
    minQuantity: 5,
    currentQuantity: 15,
    lastPurchasePrice: 2500,
    lastVendor: 'ABC Supplies',
    barcode: 'TON-12345',
    part_name: 'Toner Cartridge',
    quantity: 15,
    min_stock: 5,
    purchase_price: 2500,
    part_number: 'TON-12345',
    compatible_models: ['IR2525', 'IR2530'],
    brand_id: 'brand-1',
    model_id: 'model-1'
  },
  {
    id: '2',
    name: 'Drum Unit',
    category: 'Drum',
    brand: 'HP',
    model: 'LaserJet Pro',
    currentStock: 8,
    minStockLevel: 3,
    maxStockLevel: 20,
    reorderPoint: 5,
    unitCost: 3500,
    unitPrice: 4200,
    location: 'Warehouse B',
    lastRestocked: '2023-02-10',
    createdAt: '2023-01-15',
    modelId: 'model-2',
    brandId: 'brand-2',
    type: 'Drum',
    minQuantity: 3,
    currentQuantity: 8,
    lastPurchasePrice: 3500,
    lastVendor: 'XYZ Electronics',
    barcode: 'DRM-67890',
    part_name: 'Drum Unit',
    quantity: 8,
    min_stock: 3,
    purchase_price: 3500,
    part_number: 'DRM-67890',
    compatible_models: ['LaserJet Pro', 'LaserJet Elite'],
    brand_id: 'brand-2',
    model_id: 'model-2'
  },
  {
    id: '3',
    name: 'Fuser Assembly',
    category: 'Fuser',
    brand: 'Xerox',
    model: 'WorkCentre',
    currentStock: 5,
    minStockLevel: 2,
    maxStockLevel: 15,
    reorderPoint: 3,
    unitCost: 5000,
    unitPrice: 6000,
    location: 'Warehouse A',
    lastRestocked: '2023-03-05',
    createdAt: '2023-02-01',
    modelId: 'model-3',
    brandId: 'brand-3',
    type: 'Fuser',
    minQuantity: 2,
    currentQuantity: 5,
    lastPurchasePrice: 5000,
    lastVendor: 'Tech Parts Inc',
    barcode: 'FUS-24680',
    part_name: 'Fuser Assembly',
    quantity: 5,
    min_stock: 2,
    purchase_price: 5000,
    part_number: 'FUS-24680',
    compatible_models: ['WorkCentre 3345', 'WorkCentre 3325'],
    brand_id: 'brand-3',
    model_id: 'model-3'
  }
];
