// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://klieshkrqryigtqtshka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsaWVzaGtycXJ5aWd0cXRzaGthIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzUxODIsImV4cCI6MjA1OTk1MTE4Mn0.45vdOu9sWjNG9vpDSl637vjRDkeJbJ-wTxRk-cm7ADY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);